### ISSUE TITLE
Windows Run Ubuntu - Winse Blog

### ISSUE THREAD

**Issue by winse** [winse/winse.github.com#8]
http://winseliu.com/blog/2017/10/30/windows-run-ubuntu/

**Comment by buchijiang** [comment]
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running
你难道没遇到吗？

**Comment by winse** [comment]
@buchijiang 你要用管理员权限启动shell。普通权限启动shell，命令用sudo也不行的。

![image](https://user-images.githubusercontent.com/667902/40463222-953910dc-5f46-11e8-9702-b8a8fd2e699c.png)

![image](https://user-images.githubusercontent.com/667902/40463246-c77c5fe0-5f46-11e8-82ff-1a40b90a7731.png)

**Comment by buchijiang** [comment]
恍然大悟，非常感谢，这个问题很多人都遇到了，按你说的管理员运行，解决了

**Comment by buchijiang** [comment]
我又遇到了新的问题

![_20180531090059](https://user-images.githubusercontent.com/13143897/40755481-39c3378a-64b1-11e8-88e7-3d9a7a0ff959.png)

**Comment by winse** [comment]
@buchijiang 你先pull下来再run看看。（我的docker版本旧一点点）

```
winse@DESKTOP-ADH7K1Q:~$ sudo docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

![image](https://user-images.githubusercontent.com/667902/40885309-872232f4-6756-11e8-9465-e50041ba55cc.png)

**Comment by buchijiang** [comment]
@winse 拉不下来，是不是还有什么点没Get到

**Comment by winse** [comment]
@buchijiang https://stackoverflow.com/a/42785775/5697508 看看你的 `/var/lib/docker`  的权限。

**Comment by buchijiang** [comment]
@winse 试了，不行。有点蛋疼

**Comment by winse** [comment]
@buchijiang 加我QQ: 251788991 远程给你看一下。

**Comment by buchijiang** [comment]
这个问题已经解决了，最新版的docker应该是不支持默认的内核，换了个docker版本解决 如下图，这三个版本都是可以的，直接给出安装命令 `sudo apt-get install docker-ce=17.03.2~ce-0~ubuntu-xenial`

![image](https://user-images.githubusercontent.com/13143897/41101211-1a4ecd48-6a96-11e8-8371-ea10ccafa04e.png)
